In [49]:
import os
import numpy as np
import pandas as pd
import multiprocessing as mp

In [2]:
# set home directory
home_path = os.getcwd()[:os.getcwd().find('Code/python/obf_autax/ekl')-1]
# set raw_path
raw_path = os.path.join(home_path, 'Data', 'obf_autax', 'ekl', 'TO_1310_12_roh_20200828.XLS')
# set raw_path
ekl_path = os.path.join(home_path, 'Data', 'obf_autax', 'ekl', 'output', 'ekl_TO1310_12.csv')
# set raw_path
bg_path = os.path.join(home_path, 'Data', 'obf_autax', 'bg', 'tax_171_12_20200831.csv')

In [3]:
wo_data = pd.read_csv(raw_path, sep='\t', encoding = "ISO-8859-1", decimal=',', error_bad_lines=False)

/home/philipp/miniconda3/envs/gis/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3071: DtypeWarning: Columns (40,149) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [4]:
wo_data.head()

,Merkmalausprägung,AuswKatTyp,Teiloperats-ID,Forstbetrieb,Debitor,TO-Bezeichnung,Status,Beg. Laufzeit,Ende Laufzeit,Operat-ID,...,Zeile1,Zeile2,Zeile3,Zeile4,Zeile5,Zeile6,Zeile7,Zeile8,Bestockungsziel,Flächenanteil
0,0,NaN,1310,171,220442,FE 2020,1,01.01.2021,31.12.2030,0,...,"ST STOE 81/72, breiter tls steiniger Rücken i...",unter Str,BE mehr BU im N sowie an B1 - dort weniger SS...,Windschutz für B1,MA keinesfalls DF od dgl da labil und windexpo...,Maßnahmen auf B1 abstimmen,NaN,NaN,7FI 3LA,0.0
1,0,NaN,1310,171,220442,FE 2020,1,01.01.2021,31.12.2030,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2,0,NaN,1310,171,220442,FE 2020,1,01.01.2021,31.12.2030,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
3,0,NaN,1310,171,220442,FE 2020,1,01.01.2021,31.12.2030,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,0,NaN,1310,171,220442,FE 2020,1,01.01.2021,31.12.2030,0,...,"BE im N etw älter mit kaum LH, im SO etw jüng...","LÄ, alte SS",NaN,NaN,NaN,NaN,NaN,NaN,8FI 2LA,0.0

In [35]:
wo_data.columns[100:200]

Index(['Erfassungsstatus.3', 'Storno.2', 'GUID.5', 'GUID.6', 'Forstbetrieb.4',
       'Teiloperats-ID.4', 'Forstrevier.3', 'Abteilung.3', 'Unterabteil..3',
       'Teilfl..3', 'Best.-Schicht.2', 'Nutzungsnummer', 'Maßnahmenart',
       'Massnahme geplant', 'Massnahmengruppe', 'Angriffsfläche', 'Nutzung LH',
       'Nutzung NH', 'Nutzungssumme', 'Nutzdringlichkeit', 'Bewpfl.',
       'Zeitpunkt', 'Rückungsart', 'Schlägerungsart', 'Erfassungsstatus.4',
       'Storno.3', 'Nutztext', 'Alter der 1. Schicht', 'TAX: Altersklasse',
       'Repr. Fläche Schicht', 'Produktionskategorie', 'Geschäftsjahr',
       'Abmaßbeleg', 'Maßnahme', 'Geschäftsfeld', 'Bezeichnung',
       'Pflanzen Ist', 'Baumarten Ist', 'Repr. Fläche Baumart',
       'Ertragstafelnummer', 'Ertragstafelbezeich', 'Anmerkung', 'Zeile1',
       'Zeile2', 'Zeile3', 'Zeile4', 'Zeile5', 'Zeile6', 'Zeile7', 'Zeile8',
       'Bestockungsziel', 'Flächenanteil'],
      dtype='object')

In [39]:
wo_data = wo_data[['Waldort', 'Nutzungsnummer', 'Maßnahmenart',
       'Massnahme geplant', 'Massnahmengruppe', 'Angriffsfläche', 'Nutzung LH',
       'Nutzung NH', 'Nutzungssumme', 'Nutzdringlichkeit', 'Bewpfl.',
       'Zeitpunkt', 'Rückungsart', 'Schlägerungsart', 'Nutztext']]

In [41]:
wo_data = wo_data[wo_data['Nutzungsnummer'] > 0]

In [ ]:
# ekl

In [30]:
ekl_data = pd.read_csv(ekl_path, sep=',')

In [31]:
ekl_data.head()

,Forstbetrieb.1,Teiloperats-ID.1,Forstrevier,Abteilung,Unterabteil.,Teilfl.,WE-Typ,Betriebsklasse,Umtriebszeit,Nebengrund Art,...,TA_v,LA_ekl,LA_g,LA_v,KI_ekl,KI_g,KI_v,SK_ekl,SK_g,SK_v
0,171,1310,12,211,D,2,WO,9010.0,140,NaN,...,95.126857,6.940336,20.565444,76.108389,7.467464,22.511742,65.432155,4.880751,22.300243,124.839236
1,171,1310,12,203,F,1,WO,9040.0,160,NaN,...,0.000000,0.000000,0.000000,0.000000,2.482426,27.063888,200.181956,4.029128,28.328164,255.534147
2,171,1310,12,292,N,1,WO,9010.0,160,NaN,...,186.036357,4.635293,27.426115,193.289362,3.151578,26.721427,184.869826,4.230863,28.209626,245.899691
3,171,1310,12,207,I,3,WO,9010.0,120,NaN,...,95.362983,22.411997,29.860158,309.687134,22.265487,58.855223,100.952217,17.873331,36.977863,311.170617
4,171,1310,12,211,D,3,WO,9010.0,140,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [43]:
ekl_data.columns

Index(['Forstbetrieb.1', 'Teiloperats-ID.1', 'Forstrevier', 'Abteilung',
       'Unterabteil.', 'Teilfl.', 'WE-Typ', 'Betriebsklasse', 'Umtriebszeit',
       'Nebengrund Art', 'Ertragssituation', 'Bewirtschaftungsform',
       'Schutzwaldkategorie', 'Fläche in HA', 'Seehöhe', 'Exposition',
       'Neigung', 'Standorteinheit', 'Vegetationstyp', 'Waldtyp',
       'Wuchsgebiet', 'Überh. Laubholz', 'Überh. Nadelhz.', 'Waldort',
       'Best.-Schicht', 'Schichtanteil', 'Schichtalter', 'S-Best.grad',
       'Best.-Schicht.1', 'Baumart', 'Baumartenanteil', 'BaumartenBestockgrad',
       'Schälgrad', 'Ertragsklasse', 'Vorrat / ha', 'Laubholzvorrat / ha',
       'Nadelholzvorrat / ha', 'Vorrat am Ort', 'Laubholzvorrat Ort',
       'Nadelholzvorrat Ort', 'GSOLL / HA', 'GIST / HA', 'lauf. Zuwachs / HA',
       'DGZU / HA', 'HDZ', 'LGZ', 'WO', 'age', 'oh', 'mass', 'area', 'FI_ekl',
       'FI_g', 'FI_v', 'BU_ekl', 'BU_g', 'BU_v', 'TA_ekl', 'TA_g', 'TA_v',
       'LA_ekl', 'LA_g', 'LA_v', 'KI_ekl', 'KI_g', 'KI_v', 'SK_ekl', 'SK_g',
       'SK_v'],
      dtype='object')

In [ ]:
# bg

In [5]:
bg_data = pd.read_csv(bg_path, sep=',')

In [12]:
bg_data['WO'] = bg_data['WO'].str[1:]

In [9]:
bg_data['WO'].str[-1:]

0      0
1      K
2      2
3      3
4      4
      ..
813    K
814    2
815    3
816    4
817    K
Name: WO, Length: 818, dtype: object

In [28]:
bg_data['Waldort'] = bg_data['WO'].str[0:1].replace('K', '1') + bg_data['WO'].str[1:2].replace('K', '1') + bg_data['WO'].str[2:3].replace('K', '1') + bg_data['WO'].str[-2:-1] + bg_data['WO'].str[-1:].replace('K', '1')

In [44]:
bg_data['Waldort'] = bg_data['WO']

In [45]:
bg_data.head()

,Unnamed: 0,WO,Age,FI,TA,LA,KI,BU,DG,EI,...,IA,EL,GE,KB,RI,FA,HE,BS,KE,Waldort
0,0,201A0,0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201A0
1,0,201B1,0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201B1
2,0,201B2,0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201B2
3,0,201B3,0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201B3
4,0,201B4,0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201B4

In [51]:
# ba created by waldtyp

# set raw_path
ba_path = os.path.join(home_path, 'Data', 'obf_autax', 'ekl', 'ba', '171_12_ba.csv')

ba_data = pd.read_csv(ba_path, sep=',')

In [55]:
ba_data.columns[:100]

Index(['Merkmalausprägung', 'AuswKatTyp', 'Teiloperats-ID', 'Forstbetrieb',
       'Debitor', 'TO-Bezeichnung', 'Status', 'Beg. Laufzeit', 'Ende Laufzeit',
       'Operat-ID', 'vorgeschl. Hiebssatz', 'Verantwortlicher',
       'Erfassungsstatus', 'Migriert?', 'GUID', 'Forstbetrieb.1',
       'Teiloperats-ID.1', 'Forstrevier', 'Abteilung', 'Unterabteil.',
       'Teilfl.', 'Debitor.1', 'Bearbeitungsblock', 'WE-Typ', 'Betriebsklasse',
       'Umtriebszeit', 'Nebengrund Art', 'Ertragssituation',
       'Bewirtschaftungsform', 'Schutzwaldkategorie', 'Fläche in HA',
       'Seehöhe', 'Exposition', 'Neigung', 'Standorteinheit', 'Vegetationstyp',
       'Waldtyp', 'Wuchsgebiet', 'Überh. Laubholz', 'Überh. Nadelhz.',
       'fr. Schälschade', 'Verbissgrad', 'SchutzwaldProjNr', 'Schlussgrad',
       'Stabilität', 'VJ Bedingung', 'VJ Situation', 'Erreichbark. des BZ',
       'Selektiver Verbiss', 'Erfassungsstatus.1', 'Storno', 'Angelegt von',
       'Angelegt am', 'Uhrzeit', 'Geändert von', 'Geändert am', 'Uhrzeit.1',
       'Waldort', 'GUID.1', 'GUID.2', 'Forstbetrieb.2', 'Teiloperats-ID.2',
       'Forstrevier.1', 'Abteilung.1', 'Unterabteil..1', 'Teilfl..1',
       'Best.-Schicht', 'Debitor.2', 'Schichtanteil', 'Schichtalter',
       'S-Best.grad', 'Erfassungsstatus.2', 'Storno.1', 'GUID.3', 'GUID.4',
       'Forstbetrieb.3', 'Teiloperats-ID.3', 'Forstrevier.2', 'Abteilung.2',
       'Unterabteil..2', 'Teilfl..2', 'Best.-Schicht.1', 'Baumart',
       'Debitor.3', 'Baumartenanteil', 'BaumartenBestockgrad', 'Schälgrad',
       'Ertragsklasse', 'Vorrat / ha', 'Laubholzvorrat / ha',
       'Nadelholzvorrat / ha', 'Vorrat am Ort', 'Laubholzvorrat Ort',
       'Nadelholzvorrat Ort', 'GSOLL / HA', 'GIST / HA', 'lauf. Zuwachs / HA',
       'DGZU / HA', 'HDZ', 'LGZ'],
      dtype='object')

In [57]:
ba_data = ba_data[['Waldort', 'FI', 'KI', 'LA', 'SK', 'BU', 'ME', 'AH', 'EI', 'ES', 'BL', 'SL', 'TA',
       'KB', 'EL', 'UL', 'FA', 'PO', 'EE', 'GE', 'BI', 'AS', 'NU', 'sum']]

In [58]:
print(wo_data.shape)
print(ekl_data.shape)
print(bg_data.shape)
print(ba_data.shape)

(313, 15)
(834, 69)
(818, 48)
(834, 24)

In [59]:
merge_data = pd.merge(ekl_data, ba_data, how='left', on='Waldort')

In [60]:
merge_data = pd.merge(merge_data, bg_data, how='left', on='Waldort')

In [61]:
merge_data = pd.merge(merge_data, wo_data, how='left', on='Waldort')

In [62]:
data_path = os.path.join(home_path, 'Data', 'obf_autax')
merge_data.to_csv(data_path + "/merge_171_12.csv", index=False)

In [ ]:
alter_data = wo_data.copy()

alter_data.drop(['Best.-Schicht.2', 'Nutzungsnummer',
           'Maßnahmenart', 'Massnahme geplant', 'Massnahmengruppe',
           'Angriffsfläche', 'Nutzung LH', 'Nutzung NH', 'Nutzungssumme',
           'Nutzdringlichkeit', 'Bewpfl.', 'Zeitpunkt', 'Rückungsart',
           'Schlägerungsart', 'Repr. Fläche Schicht', 'Maßnahme', 'Geschäftsfeld',
           'Bezeichnung', 'Pflanzen Ist', 'Baumarten Ist', 'Repr. Fläche Baumart',
           'Flächenanteil'], axis=1, inplace=True)

alter_data['age'] = self.alter_data['Schichtalter']

# get all wo
wos = self.alter_data['WO'].unique()
# make column oh
alter_data['oh'] = 0
alter_data['area'] = 0

# merge data: age + height
# get list of wo in hight dataset
hight_wo = self.hight_data['wo'].unique()

for wo in wos:
    if wo in hight_wo:
        wo_hight = self.hight_data[self.hight_data['wo'] == wo]

        if wo_hight.shape[0] == 1:
            # set oh and area
            self.alter_data.loc[self.alter_data['WO'] == wo, 'oh'] = wo_hight.iloc[0, 1]
            self.alter_data.loc[self.alter_data['WO'] == wo, 'area'] = wo_hight.iloc[0, 2]
        else:
            # set oh and area
            self.alter_data.loc[self.alter_data['WO'] == wo, 'oh'] = self.wavg(wo_hight, 'oh', 'area')
            self.alter_data.loc[self.alter_data['WO'] == wo, 'area'] = wo_hight.iloc[:, 2].sum()

self.alter_data.loc[self.alter_data['oh'] < 1, 'age'] = 6

In [ ]:
self.hight_data = pd.read_csv(self.input_path_hight, sep=',', error_bad_lines=False) # encoding = "ISO-8859-1"
self.alter_data = pd.read_csv(self.input_path_age, sep=',', error_bad_lines=False)